package com.example.speedysafe.ui.weather;

import static android.content.Context.MODE_PRIVATE;

import android.content.SharedPreferences;
import android.location.Location;
import android.location.LocationListener;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;
import com.example.speedysafe.APIKey;
import com.example.speedysafe.databinding.FragmentWeatherBinding;
import com.squareup.picasso.Picasso;

import org.json.JSONException;
import org.json.JSONObject;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

public class WeatherFragment extends Fragment{

    private FragmentWeatherBinding binding;
    SharedPreferences sharedPreferences;
    SharedPreferences.Editor sharedPreferenceEditor;

    public View onCreateView(@NonNull LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

        binding = FragmentWeatherBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    String getItemFromSharedPreference(String key){
        return sharedPreferences.getString(key, "");
    }

    @Override
    public void onStart() {
        sharedPreferences = requireContext().getSharedPreferences("SpeedySafe", MODE_PRIVATE);
        sharedPreferenceEditor = sharedPreferences.edit();

        String latFetch = getItemFromSharedPreference("lat");
        if(latFetch.isEmpty()) latFetch = "28.736896";

        String longFetch = getItemFromSharedPreference("long");
        if(longFetch.isEmpty()) longFetch = "77.111996";

        getResultFromAPI(Double.parseDouble(latFetch), Double.parseDouble(longFetch));

        super.onStart();
    }

    public String getCurrentDate() {
        Calendar calendar = Calendar.getInstance();
        Date date = calendar.getTime();
        DateFormat dateFormat = new SimpleDateFormat("dd");
        return new SimpleDateFormat("EE", Locale.ENGLISH).format(date.getTime()) + ", " + new SimpleDateFormat("MMM").format(calendar.getTime()) + " " + dateFormat.format(date) + "th" + " " + (date.getYear() + 1900);
    }

    /**Function to get the result generated by API**/
    public void getResultFromAPI(double latitude, double longitude) {
        // API call to get the location of current user

        String resultCall = "https://api.openweathermap.org/data/2.5/weather?lat=" + latitude + "&lon=" + longitude + "&appid=" + APIKey.APIKEY + "&units=" + "metric";
        StringRequest stringRequestFirst = new StringRequest(Request.Method.GET, resultCall, response -> {
            try {
                // object received
                JSONObject jsonObject = new JSONObject(response);
                // extracting the current JSON object
                String city = jsonObject.getString("name");

            } catch (JSONException e) {
                e.printStackTrace();
                Toast.makeText(requireContext(), e.getMessage(), Toast.LENGTH_SHORT).show();
            }

        }, error -> Toast.makeText(requireContext(), error.getMessage(), Toast.LENGTH_SHORT).show());
        RequestQueue requestQueueOne = Volley.newRequestQueue(requireContext());
        requestQueueOne.add(stringRequestFirst);

        //API call to get the other weather parameter of current location
        String LAT_LONG = "https://api.openweathermap.org/data/2.5/onecall?lat=" + latitude + "&lon=" + longitude + "&appid=" + APIKey.APIKEY + "&units=" + "metric";
        StringRequest stringRequestTwo = new StringRequest(Request.Method.GET, LAT_LONG, response -> {
            try {
                // object received
                JSONObject jsonObject = new JSONObject(response);
                jsonObject = jsonObject.getJSONObject("current");

                // extracting the current JSON object
                JSONObject objectWeather = jsonObject.getJSONArray("weather").getJSONObject(0);

                // code to fetch the image of weather using the weather object
                String imgCode = objectWeather.getString("icon");
                String url = "https://openweathermap.org/img/wn/" + imgCode + "@4x.png";

                // getting results like windSpeed, temperature, humidity, etc.
                String wind_speed = jsonObject.getString("wind_speed");
                String temp = jsonObject.getString("temp");
                String feelsLike = jsonObject.getString("feels_like");
                String pressure = jsonObject.getString("pressure");

                // finding the level of UVI using the result from API
                int uvi = jsonObject.getInt("uvi");
                String uviResult = "";
                // uvi ranges
                if (uvi >= 0 && uvi <= 2) {
                    uviResult = "Low";
                } else if (uvi >= 3 && uvi <= 5) {
                    uviResult = "Moderate";
                } else if (uvi >= 6 && uvi <= 7) {
                    uviResult = "High";
                } else {
                    uviResult = "Very High";
                }

                String humidity = jsonObject.getString("humidity");
                String visibility = jsonObject.getString("visibility");

                //making the views visible and progress bar invisible
                binding.layoutItems.setVisibility(View.VISIBLE);
                binding.progressBar.setVisibility(View.GONE);
                Picasso.get().load(url).into(binding.imageWeather);

                //code to display the fetched data from the API
                binding.textFeelsLike.setText(feelsLike + " °C");
                binding.textPressure.setText(pressure + " hPa");
                binding.textUV.setText(uviResult);
                binding.textDate.setText(getCurrentDate());
                binding.textWind.setText(wind_speed + " km/hr");

                binding.tempText.setText(Float.valueOf(temp).intValue() + "");
                binding.textVisibility.setText(((Float.valueOf(visibility).intValue()) / 1000) + " km");
                binding.textHumidity.setText(humidity + " %");

            } catch (JSONException e) {
                e.printStackTrace();
                Toast.makeText(requireContext(), e.getMessage(), Toast.LENGTH_SHORT).show();
            }

        }, error -> Toast.makeText(requireContext(), error.getMessage(), Toast.LENGTH_SHORT).show());

        RequestQueue requestQueueTwo = Volley.newRequestQueue(requireContext());
        requestQueueTwo.add(stringRequestTwo);

    }
}